services:

  mysql:
    image: mysql:8
    container_name: mysql-container

    environment:
      MYSQL_ROOT_PASSWORD: 7432
      MYSQL_DATABASE: ticket_system

    ports:
      - "3307:3306"

  springboot:
    build: .
    container_name: springboot-container

    ports:
      - "9090:8080"

    depends_on:
      - mysql

    restart: on-failure